'use strict';
const fullName = 'Enrique';
const isCool = true;
const totalPets = 3;
console.log('My name is ', fullName);
console.log('value of isCool: ', isCool);
console.log('value of totalPets ', totalPets);
console.log('typeof fullName: ', typeof fullName);
console.log('typeof isCool: ', typeof isCool);
console.log('typeof totalPets ', typeof totalPets);
const empty = null;
console.log('value of empty ', empty);
console.log('typeof empty: ', typeof empty);
let nothing;
console.log('value of nothing: ', nothing);
console.log('typeof of nothing ', typeof nothing);
