'use strict';
const colors = ['red', 'white', 'blue'];
const firstColor = colors[0];
const secondColor = colors[1];
const lastColor = colors[colors.length - 1];
const America = `America is ${firstColor}, ${secondColor}, and ${lastColor}`;
console.log('colors[0] ', firstColor);
console.log('colors[1] ', secondColor);
console.log('colors[2] ', lastColor);
console.log(America);
colors[colors.length - 1] = 'green';
const Mexico = `Mexico is ${firstColor}, ${secondColor}, and ${colors[2]}`;
console.log(Mexico);
console.log('value of colors ', colors);
console.log('typeof colors ', typeof colors);
const students = ['Aizen', 'Jack', 'Kazuma', 'Eren'];
const numberOfStudents = students.length;
console.log(`There are ${numberOfStudents} students in the class`);
const lastIndex = numberOfStudents - 1;
const lastStudent = students[lastIndex];
console.log('The last student is ', lastStudent);
console.log('Value of students ', students);
console.log('typeof students ', typeof students);
