'use strict';
const width = 10;
const height = 20;
const area = width * height;
console.log('The area is ', area);
console.log('Typeof area ', typeof area);
const bill = 100;
const payment = 200;
const change = payment - bill;
console.log('Change is ', change);
console.log('typeof change ', typeof change);
const quizzes = 50;
const midterm = 70;
const final = 85;
const grade = (quizzes + midterm + final) / 3;
console.log('Grade is ', grade);
console.log('typeof grade ', typeof grade);
const firstName = 'Enrique';
const lastName = ' Canel';
const fullName = firstName + lastName;
console.log("Hi I'm ", fullName);
console.log('typeof fullName ', typeof fullName);
const pH = 7;
const isAcidic = pH < 7;
console.log('value of isAcidic ', isAcidic);
console.log('typeof isAcidic ', typeof isAcidic);
const headCount = 300;
const isSparta = headCount == 300;
console.log('value of isSparta ', isSparta);
console.log('typeof isSparta ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT!';
console.log('value of motto ', motto);
console.log('typeof motto ', typeof motto);
